### ISSUE TITLE
warning about KEYSIZE

### ISSUE THREAD

**Issue by tomkerswill** [mikeblum/acme-api-gateway#2]
API Gateway only supports certificates that have a key size of 2048; whereas by default, dehydrated ses KEYSIZE=4096.  That means that by default, the certificate won't work and will generate an error when it's added to API Gateway.

The solution is to simply enter KEYSIZE=2048 in a config file for dehydrated

I'm not sure if this hook can change that, because it's with dehydrated. But it would be good if it can display a warning to the user if the keysize of the certificate is wrong...

**Comment by mikeblum** [comment]
Good point - I set the keysize in the code to align with what AWS expects: `KEYSIZE="2048"` in test.conf and prod.conf. I found that number buried in the certificates expected by Route 53.

acme-api-gateway/conf/test.conf
acme-api-gateway/conf/prod.conf

As far as I know, the end-user would never be updating the keysize and we can keep it as a configuration detail in the code.
